version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-docker
    ports:
      - "1884:1883"  # Cambiamos el puerto externo para evitar conflicto
      - "9001:9001"  # Puerto para Websockets (opcional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
